-- Ativa funções de hash
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE usuario (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username    TEXT NOT NULL UNIQUE,
  nome        TEXT NOT NULL,
  password_hash TEXT NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Usuário de desenvolvimento: username 'admin', senha 'senha123'
INSERT INTO usuario (username, nome, password_hash)
VALUES ('admin', 'Administrador', crypt('senha123', gen_salt('bf')));
