-- public.departamento definition

-- Drop table

-- DROP TABLE public.departamento;

CREATE TABLE public.departamento (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	nome text NOT NULL,
	sigla text NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	updated_at timestamptz DEFAULT now() NOT NULL,
	CONSTRAINT ck_departamento_sigla_len CHECK (((sigla IS NULL) OR ((length(sigla) >= 1) AND (length(sigla) <= 10)))),
	CONSTRAINT departamento_nome_key UNIQUE (nome),
	CONSTRAINT departamento_pkey PRIMARY KEY (id)
);

-- Table Triggers

create trigger tg_departamento_updated_at before
update
    on
    public.departamento for each row execute function set_updated_at();


-- public.flyway_schema_history definition

-- Drop table

-- DROP TABLE public.flyway_schema_history;

CREATE TABLE public.flyway_schema_history (
	installed_rank int4 NOT NULL,
	"version" varchar(50) NULL,
	description varchar(200) NOT NULL,
	"type" varchar(20) NOT NULL,
	script varchar(1000) NOT NULL,
	checksum int4 NULL,
	installed_by varchar(100) NOT NULL,
	installed_on timestamp DEFAULT now() NOT NULL,
	execution_time int4 NOT NULL,
	success bool NOT NULL,
	CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank)
);
CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);


-- public.usuario definition

-- Drop table

-- DROP TABLE public.usuario;

CREATE TABLE public.usuario (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	username text NOT NULL,
	nome text NOT NULL,
	password_hash text NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	CONSTRAINT usuario_pkey PRIMARY KEY (id),
	CONSTRAINT usuario_username_key UNIQUE (username)
);


-- public.aluno definition

-- Drop table

-- DROP TABLE public.aluno;

CREATE TABLE public.aluno (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	ra varchar(20) NOT NULL,
	nome text NOT NULL,
	email text NULL,
	departamento_id int8 NOT NULL,
	data_nascimento date NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	updated_at timestamptz DEFAULT now() NOT NULL,
	CONSTRAINT aluno_email_key UNIQUE (email),
	CONSTRAINT aluno_pkey PRIMARY KEY (id),
	CONSTRAINT aluno_ra_key UNIQUE (ra),
	CONSTRAINT fk_aluno_departamento FOREIGN KEY (departamento_id) REFERENCES public.departamento(id) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX ix_aluno_departamento ON public.aluno USING btree (departamento_id);
CREATE UNIQUE INDEX ux_aluno_email_lower ON public.aluno USING btree (lower(email)) WHERE (email IS NOT NULL);

-- Table Triggers

create trigger tg_aluno_updated_at before
update
    on
    public.aluno for each row execute function set_updated_at();


-- public.prova definition

-- Drop table

-- DROP TABLE public.prova;

CREATE TABLE public.prova (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	departamento_id int8 NOT NULL,
	titulo text NOT NULL,
	"data" date NOT NULL,
	descricao text NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	updated_at timestamptz DEFAULT now() NOT NULL,
	CONSTRAINT prova_pkey PRIMARY KEY (id),
	CONSTRAINT uq_prova_unica_por_dep_dia UNIQUE (departamento_id, titulo, data),
	CONSTRAINT fk_prova_departamento FOREIGN KEY (departamento_id) REFERENCES public.departamento(id) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX ix_prova_departamento_data ON public.prova USING btree (departamento_id, data);

-- Table Triggers

create trigger tg_prova_updated_at before
update
    on
    public.prova for each row execute function set_updated_at();


-- public.nota definition

-- Drop table

-- DROP TABLE public.nota;

CREATE TABLE public.nota (
	aluno_id int8 NOT NULL,
	prova_id int8 NOT NULL,
	valor numeric(5, 2) NOT NULL,
	observacao text NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	updated_at timestamptz DEFAULT now() NOT NULL,
	CONSTRAINT ck_nota_valor CHECK (((valor >= (0)::numeric) AND (valor <= (10)::numeric))),
	CONSTRAINT pk_nota PRIMARY KEY (aluno_id, prova_id),
	CONSTRAINT fk_nota_aluno FOREIGN KEY (aluno_id) REFERENCES public.aluno(id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_nota_prova FOREIGN KEY (prova_id) REFERENCES public.prova(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Table Triggers

create trigger tg_nota_updated_at before
update
    on
    public.nota for each row execute function set_updated_at();
create trigger tg_nota_mesmo_departamento before
insert
    or
update
    on
    public.nota for each row execute function check_nota_mesmo_departamento();